# Generated by Django 3.2 on 2023-01-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('category_description', models.TextField(max_length=200, verbose_name='Описание')),
                ('category_slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100, verbose_name='Название цвета')),
                ('color_slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Цвет товара',
                'verbose_name_plural': 'Цвета товара',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Ширина')),
                ('length', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Длина')),
                ('thickness', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Толщина')),
            ],
            options={
                'verbose_name': 'Размер товара',
                'verbose_name_plural': 'Размеры товара',
            },
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_name', models.CharField(max_length=147, verbose_name='Должность')),
                ('salary', models.IntegerField(default=0, verbose_name='Зарплата')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=147, verbose_name='Название товара')),
                ('description', models.TextField()),
                ('prod_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productcolor')),
                ('prod_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productsize')),
            ],
        ),
    ]
