# Generated by Django 4.1.4 on 2023-01-12 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='product_description',
        ),
        migrations.AddField(
            model_name='category',
            name='create_ad',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_slug',
            field=models.SlugField(default=1, max_length=120, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancies',
            name='vac_slug',
            field=models.SlugField(default=1, max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
